### PR TITLE
Release v0.52.0

### PR DESCRIPTION
**Pull request by taylorbot**

### CODE REVIEW

**Review by ssyno — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Sorry, there was an issue with capa private tests so I cancelled your in-progress test run. 

Re-triggering now that the issue is resolved:

/run cluster-test-suites

**Comment by nprokopic** [comment]
@AverageMarcus @tuladhar any concerns with merging this?

**Comment by nprokopic** [comment]
Assuming Puru would also like to have this released, since he triggered the release, so merging this 😬

**Comment by tuladhar** [comment]
> Assuming Puru would also like to have this released, since he triggered the release, so merging this 😬 

Yes, yes. Thanks for taking care 🙏

**Pull request merged**
