### PR TITLE
Add k8s-dns-node-cache-app

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/roadmap/issues/3222

Verified by adding log directive to the corefile. Works ok.

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Comment by calvix** [comment]
WOuld be great to see green mark from e2e tets

**Review by ced0ps — APPROVED** [review]

**Comment by kopiczko** [comment]
```
 ✖ [AfterSuite] (1809.739583402)
	Expected success, but got an error:
	    <context.deadlineExceededError>: 
	    context deadline exceeded
	    {}
```

Is that ok?

**Comment by mcharriere** [comment]
yes, it look related that. The relevant issue is: https://github.com/giantswarm/giantswarm/issues/30181

**Pull request merged**
