### PR TITLE
Upgrade observability bundle

### PR DESCRIPTION
**Pull request by QuentinBisson**
### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

### CODE REVIEW

**Comment by fiunchinho** [comment]
We use `grizzly` for the e2e tests and it's currently being recreated so we can't run tests atm.

**Comment by QuentinBisson** [comment]
Makes sense :D

**Comment by fiunchinho** [comment]
Can you test it manually?

**Comment by QuentinBisson** [comment]
Well, yes but I'd rather not do it on all providers :D

**Comment by fiunchinho** [comment]
`grizzly` is being recreated this week. I don't know how urgent this ugprade is, but if it's not urgent you could wait until grizzly is up and running again.

**Comment by QuentinBisson** [comment]
Sure thing :)

**Comment by fiunchinho** [comment]
Superseeded by https://github.com/giantswarm/default-apps-aws/pull/169

**Pull request closed without merging**
