### PR TITLE
Disable observability-bundle

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Disable  observability-bundle #102

### CODE REVIEW

**Review by fiunchinho — CHANGES_REQUESTED** [review]
I'd prefer to remove it entirely than having more logic to decide which apps get installed.

**Comment by calvix** [comment]
> I'd prefer to remove it entirely than having more logic to decide which apps get installed.

+1 , I don't see reason why we should have an apps that are not installed, that feels weird

**Comment by mcbenjemaa** [comment]
fine with me

**Review by calvix — APPROVED** [review]

**Comment by mcbenjemaa** [comment]
@fiunchinho

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
