### PR TITLE
Enable cilium network policies for cert manager

### PR DESCRIPTION
**Pull request by ubergesundheit**
### What this PR does / why we need it

This PR builds on #302 and enables cilium NetworkPolicies for cert-manager-app. It also upgrades cert-manager-app to 3.2.0

Related: giantswarm/giantswarm#27963

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by Gacko — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]
Tests are flaky, but it's hard to investigate since our previous release of `default-apps-aws` is using `helm force`. So let's merge this and release it so we can investigate without `helm force` in the picture.

**Pull request merged**
