### PR TITLE
Release v0.31.0

### PR DESCRIPTION
**Pull request by taylorbot**

### CODE REVIEW

**Comment by fiunchinho** [comment]
e2e tests on grizzly are currently broken https://gigantic.slack.com/archives/C02GDJJ68Q1/p1691057634522609

**Comment by bdehri** [comment]
@fiunchinho should I wait for them to be fixed?

**Review by AndiDog — APPROVED** [review]

**Comment by fiunchinho** [comment]
I would hold it for now.

**Pull request merged**
