### PR TITLE
Add mention to e2e pipelines in README

### PR DESCRIPTION
**Pull request by fiunchinho**
### Checklist

- [ ] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/test create
/test upgrade

### CODE REVIEW

**Comment by fiunchinho** [comment]
hey @QuentinBisson I'm trying to explain better how the pipelines work, any feedback is welcome.

**Comment by QuentinBisson** [comment]
Thanks a lot Jose this is definitely helps but why did I also found the build in prow? 

Also, would it be possible to have a link to the pipeline run in the github issue so we can check directly?

**Comment by fiunchinho** [comment]
> Thanks a lot Jose this is definitely helps but why did I also found the build in prow?

What do you mean? We use `prow` to communicate between PRs and tekton.

> Also, would it be possible to have a link to the pipeline run in the github issue so we can check directly?

I don't think it's possible at the moment without some effort, and we currently don't have the bandwidth.

**Comment by QuentinBisson** [comment]
Well, you were mentionning teckton and not prow hence my question :)

I'm fine without the links but for people that do not use tekton or prow on a regular basis, having a quick how to find your pipeline section would help in the doc :)

**Comment by fiunchinho** [comment]
I'll merge this for now and see if I can document it better.

**Pull request merged**
