### PR TITLE
Add dependencies on `prometheus-operator-crd` for quicker deployment

### PR DESCRIPTION
**Pull request by AndiDog**
### What this PR does / why we need it

Similar to https://github.com/giantswarm/default-apps-azure/pull/213. This makes CAPZ/CAPA default apps consistent.

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AndiDog** [comment]
Oops, I added `dependsOn: prometheus-operator-crd` to `observability-bundle` but that's the bundle which installs the CRDs 🤣

**Comment by AndiDog** [comment]
Tests ran with old commit, trying again

 /run cluster-test-suites

**Review by calvix — APPROVED** [review]

**Pull request merged**
