### PR TITLE
fix-psp-values-for-observability-bundle

### PR DESCRIPTION
**Pull request by QuentinBisson**
### What this PR does / why we need it

Towards https://github.com/giantswarm/giantswarm/issues/29529

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas running this on a CAPI WC resulted in:

- observability-bundle-user-values:
```
apiVersion: v1
data:
  values: |
    userConfig:
      kubePrometheusStack:
        configMap:
          values:
            global:
              rbac:
                pspEnabled: true
            kube-prometheus-stack:
              grafana:
                rbac:
                  pspEnabled: true
              kube-state-metrics:
                podSecurityPolicy:
                  enabled: true
              prometheus-node-exporter:
                rbac:
                  pspEnabled: true
      prometheusAgent:
        configMap:
          values:
            prometheus-agent:
              psp:
                enabled: true
      promtail:
        configMap:
          values:
            promtail:
              rbac:
                pspEnabled: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: quentin-default-apps
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2024-01-16T22:24:20Z"
  labels:
    app-operator.giantswarm.io/watching: "true"
    app.giantswarm.io/branch: ""
    app.giantswarm.io/commit: ""
    app.kubernetes.io/instance: quentin-default-apps
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: default-apps-aws
    app.kubernetes.io/version: 0.41.0-d540398c668d556771699e864d370c685d7668c8
    application.giantswarm.io/team: phoenix
    giantswarm.io/cluster: quentin
    giantswarm.io/managed-by: quentin-default-apps
    giantswarm.io/organization: giantswarm
    giantswarm.io/service-type: managed
    helm.sh/chart: default-apps-aws-0.41.0-d540398c668d556771699e864d370c685d7668c
  name: quentin-observability-bundle-user-values
  namespace: org-giantswarm
  resourceVersion: "1158700864"
  uid: ef7552b6-4eca-4766-b91a-770769a87640
```

- promtail-user-values

```
apiVersion: v1
data:
  values: |
    ciliumNetworkPolicy:
      enabled: true
    promtail:
      networkPolicy:
        enabled: false
      rbac:
        pspEnabled: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: quentin-observability-bundle
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2024-01-16T22:25:45Z"
  labels:
    app-operator.giantswarm.io/watching: "true"
    app.kubernetes.io/instance: quentin-observability-bundle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: observability-bundle
    app.kubernetes.io/version: 1.0.0
    application.giantswarm.io/team: atlas
    giantswarm.io/cluster: quentin
    giantswarm.io/managed-by: quentin-observability-bundle
    giantswarm.io/organization: ""
    giantswarm.io/service-type: managed
    helm.sh/chart: observability-bundle-1.0.0
  name: quentin-promtail-user-values
  namespace: org-giantswarm
  resourceVersion: "1158704005"
  uid: 96b3382c-2f47-436b-9ad5-4f3f248d58ed

- prometheus-agent-user-values

```
apiVersion: v1
data:
  values: |
    prometheus-agent:
      psp:
        enabled: true
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: quentin-observability-bundle
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2024-01-16T22:25:45Z"
  labels:
    app-operator.giantswarm.io/watching: "true"
    app.kubernetes.io/instance: quentin-observability-bundle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: observability-bundle
    app.kubernetes.io/version: 1.0.0
    application.giantswarm.io/team: atlas
    giantswarm.io/cluster: quentin
    giantswarm.io/managed-by: quentin-observability-bundle
    giantswarm.io/organization: ""
    giantswarm.io/service-type: managed
    helm.sh/chart: observability-bundle-1.0.0
  name: quentin-prometheus-agent-user-values
  namespace: org-giantswarm
  resourceVersion: "1158704024"
  uid: 8b59806d-1d8b-4e75-a352-531845457049
```

- kube-prometheus-stack-user-values

```
apiVersion: v1
data:
  values: |
    global:
      rbac:
        pspEnabled: true
    kube-prometheus-stack:
      alertmanager:
        enabled: false
      defaultRules:
        create: false
      grafana:
        enabled: false
        rbac:
          pspEnabled: true
      kube-state-metrics:
        networkPolicy:
          flavor: cilium
        podSecurityPolicy:
          enabled: true
      prometheus:
        enabled: false
      prometheus-node-exporter:
        rbac:
          pspEnabled: true
      prometheusOperator:
        networkPolicy:
          flavor: cilium
          matchLabels:
            app.kubernetes.io/instance: kube-prometheus-stack
            app.kubernetes.io/part-of: kube-prometheus-stack
            application.giantswarm.io/team: atlas
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: quentin-observability-bundle
    meta.helm.sh/release-namespace: org-giantswarm
  creationTimestamp: "2024-01-16T22:25:45Z"
  labels:
    app-operator.giantswarm.io/watching: "true"
    app.kubernetes.io/instance: quentin-observability-bundle
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: observability-bundle
    app.kubernetes.io/version: 1.0.0
    application.giantswarm.io/team: atlas
    giantswarm.io/cluster: quentin
    giantswarm.io/managed-by: quentin-observability-bundle
    giantswarm.io/organization: ""
    giantswarm.io/service-type: managed
    helm.sh/chart: observability-bundle-1.0.0
  name: quentin-kube-prometheus-stack-user-values
  namespace: org-giantswarm
  resourceVersion: "1158704015"
  uid: eff6dd9e-0505-4323-95e6-e78ca76c97f8
```

**Review by QuantumEnigmaa — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Comment by QuentinBisson** [comment]
Tests are timing out but that's not related to this change so merging

**Pull request merged**
