### PR TITLE
Enable `ciliumNetworkPolicy` for apps that support it.

### PR DESCRIPTION
**Pull request by whites11**
### What this PR does / why we need it

Towards: https://github.com/giantswarm/roadmap/issues/2860

### Checklist

- [x] Update changelog in CHANGELOG.md.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by AndiDog — APPROVED** [review]

**Review by AndiDog — APPROVED** [review]

**Comment by AndiDog** [comment]
come on...

/run cluster-test-suites

**Comment by AndiDog** [comment]
metrics-server is missing. It crashloops for a new CAPA WC. I'm pushing this change to _this PR_ and will then test it.

**Comment by AndiDog** [comment]
> metrics-server is missing. It crashloops for a new CAPA WC. I'm pushing this change to _this PR_ and will then test it.

Works fine. Let's maybe run another E2E test after the current one finishes. But currently, we exceed the limit for ACM certificates and it may fail until AWS has raised the limit (see [chat](https://gigantic.slack.com/archives/C02JTRT152L/p1705329539542849?thread_ts=1705328577.943649&cid=C02JTRT152L)).

**Review by AndiDog — APPROVED** [review]

**Review by fiunchinho — APPROVED** [review]

**Pull request merged**
