### PR TITLE
Re-enable observability-bundle.

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Re-enable observability-bundle. #108

The app-admission fix has been released: 

- https://github.com/giantswarm/app/pull/266
- https://github.com/giantswarm/app-admission-controller/releases/tag/v0.18.2

we just need the cluster-apps-operator to be released first: https://github.com/giantswarm/cluster-apps-operator/pull/308

### CODE REVIEW

**Review by QuentinBisson — APPROVED** [review]

**Comment by QuentinBisson** [comment]
We can probably deploy on grizzly so I can investigate the bundle / collection clash

**Review by fiunchinho — APPROVED** [review]
LGTM, just make sure it works this time :smile:

**Comment by fiunchinho** [comment]
@mcbenjemaa @QuentinBisson did you test it on `grizzly`? On `grizzly` , if I try to open prometheus I get this error

image

**Comment by QuentinBisson** [comment]
If prometheus is failing on grizzly, that's something else but I can take a look

**Comment by QuentinBisson** [comment]
It's missing the prometheus-remotewrite app https://github.com/giantswarm/config/tree/main/installations/grizzly/apps

**Comment by QuentinBisson** [comment]
Fixed

**Pull request merged**
